### ISSUE TITLE
Bases

### ISSUE THREAD

**Issue by halan** [TribunaDoNorte/dojo#2]
Preparei essa base [ruby+rspec](https://github.com/TribunaDoNorte/dojo/tree/master/ruby%2Brspec) para usarmos no primeiro dojo. Quem quiser criar bases com outras linguagens e outros ambientes de teste, é só fazer um pull request que eu adiciono.

Linguagens sugeridas:
- Python
- Javascript/browser
- Javascript/Node.js
- Java
- C
- C++
- Lua
- Scala
- PHP
- ...

**Comment by brennovich** [comment]
+1 para Javascript

**Comment by halan** [comment]
Js+jasmine ? Pull-request

**Comment by brunohenrique** [comment]
javascript/jasmine

node.js/jessie

**Comment by halan** [comment]
Só mandar
