### ISSUE TITLE
Nível do participante

### ISSUE THREAD

**Issue by andersonolisilva** [TribunaDoNorte/dojo#8]
Este evento dá certo pra quem tem interesse em conhecer a linguagem ou todos já estão voando no Ruby + respec? Tem que levar um ambiente já montado ou basta um notebook e disposição pra aprender?...

**Comment by halan** [comment]
Oi Anderson, todos os níveis são bem vindos, inclusível o nível 0. Não precisa levar notebook, na dinâmica do dojo é utilizado apenas um computador com um projetor, e todo mundo se reversa e programa junto, confere nas (regras)[http://github.com/tribunadonorte/dojo].

O dojo é um ótimo lugar para aprender e conhecer programadores de TODOS os níveis.

Ao final do evento iremos colocar o código aqui, então você pode clonar no seu notebook.

**Comment by halan** [comment]
https://github.com/TribunaDoNorte/dojo/tree/master/17-nov-2012#instala%C3%A7%C3%A3o-do-ruby
